import type { NextPage } from 'next';
import Head from 'next/head'
import { useState } from 'react'
import Chat from '../components/chat';
import TV from '../components/tv';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  const [chatIsHidden, setChatIsHidden] = useState<boolean>(false);

  return (
    <div>
      <Head>
        <title>VintageTV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.layout}>
        <div className={styles.tvContainer}>
          <TV />
        </div>

        <div className={styles.chatContainer + (chatIsHidden ? " " + styles.hidden : "")}>
          <Chat />
        </div>

        <button className={styles.chatToggleButton} onClick={() => {setChatIsHidden(!chatIsHidden)}}>Chat</button>
      </main>
    </div>
  )
}

export default Home
